### PR TITLE
Optimized code

### LINKED ISSUE #166: Hidden questions are shown while waiting for API results
Likely because of my changes in pull request #159 to address issue #153, questions that have replies but are still within the 24 hour period are popping up on the list UI from the time the API call is made until the time that all of the API calls are returned. To be honest, I can't really pinpoint exactly where the issue is happening.

However, I already started a rewrite of some of the question list storage code, so I'll just work the solution for issue #153 into that so that it will wipe out this bug. On the plus side, everything seems to be running a little faster with some of the rewrite stuff I've already done.

Mostly I've just been simplifying the code to replace some of the loops with the cleaner array operations like `findIndex()` and `filter()`. I already have a local test version done, so I'll do some testing with it running in the browser tomorrow and, if it works as expected, will submit a PR.

### PR DESCRIPTION
**Pull request by WesleyBranton**
I made a lot of simplifications to how the arrays are handled, particularly when it comes to cleaning old questions out of the storage. These changes should also fix #166.

I've tested the code overnight and it appears to be working as expected. I will give it the rest of the day to make sure that there are no bugs and then will merge into the master branch. Would like to do the release to AMO as soon as it's merged so that it fixes that bug.

### CODE REVIEW

**Comment by dannycolin** [comment]
Any reason you decided to use `const` (immutable) over `let`?

**Comment by WesleyBranton** [comment]
> Any reason you decided to use `const` (immutable) over `let`?
Not really. It could work either way, but they are all values that are not going to change. Just preference I guess.

**Comment by dannycolin** [comment]
Ok. Just wanted to make sure it wasn't a replace all that gone wrong :P

**Comment by WesleyBranton** [comment]
Everything appears to be working here. I'll merge it into the master branch and rebuild it with all of the changes and test it tomorrow to make 100% it's all working. Then I will push it to AMO.

**Pull request merged**
