### PR TITLE
Various UI fixes

### PR DESCRIPTION
**Pull request by WesleyBranton**
This pull request has a number of UI fixes and improvements in it. Most are for mobile, but there are some sidebar issues fixed in there too.

~Once it's merged into the main branch, an update should probably be pushed to AMO to make this version 1.4.1.~ ~Actually, hold off on the AMO update. I'm pretty sure I know what the problem is for issue 133.~ Ok, a release can be pushed to AMO once this is approved and merged. I fixed issue 133.

### CODE REVIEW

**Comment by jhonatasrm** [comment]
I really liked the changes, what do you think @dannycolin ?

🙂

**Comment by dannycolin** [comment]
Everything looks good but one small thing. I'm not sure about hiding the button in the sidebar. It isn't obvious, at first, that you can click on the question title "only" when the button is hidden. Also, it removes the indication that the action will open in a new tab.

**Comment by WesleyBranton** [comment]
> Everything looks good but one small thing. I'm not sure about hiding the button in the sidebar. It isn't obvious, at first, that you can click on the question title "only" when the button is hidden. Also, it removes the indication that the action will open in a new tab.

It's difficult to signify that it will open in a new tab without some kind of visible icon. Any ideas?

**Comment by dannycolin** [comment]
> It's difficult to signify that it will open in a new tab without some kind of visible icon. Any ideas?

Other than an icon no. Maybe we could add it, in a small form, directly at the end of the question title and give the title the same look as a like.

**Comment by WesleyBranton** [comment]
I'm going to merge this into the master branch and then we can decide how to mark the questions, if necessary.

**Pull request merged**
