### PR TITLE
Fix issue #114

### PR DESCRIPTION
**Pull request by dannycolin**

### CODE REVIEW

**Comment by jhonatasrm** [comment]
Seems the "Auto-detect" theme has some issues when installing the Add-on for the first time (popup and sidebar). I was thinking if it is not better to keep only the "Dark" and "Light" theme (both themes are perfect).

**Comment by dannycolin** [comment]
>  I was thinking if it is not better to keep only the "Dark" and "Light" theme (both themes are perfect).

We could push a release to AMO without the "auto-detect" option and re-add it later.

> Seems the "Auto-detect" theme has some issues when installing the Add-on for the first time (popup and sidebar).

Could you give me more details about the issue and the OS, FF version you've tested it on?

**Comment by jhonatasrm** [comment]
> Could you give me more details about the issue and the OS, FF version you've tested it on?

macOS Catalina version 10.15 and Firefox 71.0

Screen Shot 2019-12-09 at 12 11 48 AM
Screen Shot 2019-12-09 at 12 12 06 AM

**Comment by dannycolin** [comment]
I found the problem :). The initial value wasn't saved to the local storage. It should work now so @jhonatasrm could you retry?

**Comment by jhonatasrm** [comment]
> The initial value wasn't saved to the local storage. It should work now so @jhonatasrm could you retry?

Now it's working 😃

**Comment by jhonatasrm** [comment]
What do you think in keep the sidebar that way? I don't know, is just a suggestion to not break the layout...(maybe the logo and the 3 buttons)

Sorry for asking so many things, but I believe after this we can release the new version.

Screen Shot 2019-12-09 at 12 44 19 AM

**Comment by jhonatasrm** [comment]
It's looking amazing to me. 🙂

**Pull request merged**
